enabled: true

detection:
  enabled_types:
    - PERSON_NAME
    - BIRTH_DATE
    - BIRTH_PLACE
    - CITIZENSHIP
    - PASSPORT_NUMBER
    - PASSPORT_ISSUER
    - PASSPORT_DIVISION_CODE
    - PASSPORT_ISSUE_DATE
    - DRIVER_LICENSE
    - ADDRESS
    - EMAIL
    - PHONE
    - INN
    - BANK_CARD
    - CVV
    - PIN
    - CARDHOLDER_NAME

masking:
  PERSON_NAME: FULL_MASK
  BIRTH_DATE: FULL_MASK
  BIRTH_PLACE: FULL_MASK
  CITIZENSHIP: FULL_MASK
  PASSPORT_NUMBER: PARTIAL_MASK
  PASSPORT_ISSUER: FULL_MASK
  PASSPORT_DIVISION_CODE: FULL_MASK
  PASSPORT_ISSUE_DATE: FULL_MASK
  DRIVER_LICENSE: FULL_MASK
  ADDRESS: FULL_MASK
  EMAIL: FULL_MASK
  PHONE: PARTIAL_MASK
  INN: PARTIAL_MASK
  BANK_CARD: PARTIAL_MASK
  CVV: FULL_MASK
  PIN: FULL_MASK
  CARDHOLDER_NAME: FULL_MASK

demasking:
  enabled: true

context_rules: []